const hre = require("hardhat");
const fs  = require("fs");
const path = require("path");

async function main() {
  console.log("\n🚀 DIDPass — Smart Contract Deployment & Setup\n");
  console.log("═".repeat(65));

  const accounts    = await hre.ethers.getSigners();
  const deployer    = accounts[0]; // Admin / Contract Owner
  const tuIssuer    = accounts[1]; // Tribhuvan University
  const bankIssuer  = accounts[2]; // Nabil Bank
  const nirmal      = accounts[3]; // Demo holder — Nirmal Shrestha

  console.log("\n📋 Deployment Accounts:");
  console.log(`   Admin (Deployer):       ${deployer.address}`);
  console.log(`   Tribhuvan University:   ${tuIssuer.address}`);
  console.log(`   Nabil Bank:             ${bankIssuer.address}`);
  console.log(`   Demo Holder (Nirmal):   ${nirmal.address}`);

  // ─── 1. Deploy All Six Contracts ─────────────────────────────────────────
  console.log("\n📦 Deploying Contracts...\n");

  const deploy = async (name, ...args) => {
    const Factory  = await hre.ethers.getContractFactory(name);
    const contract = await Factory.deploy(...args);
    await contract.waitForDeployment();
    const addr = await contract.getAddress();
    console.log(`   ✅ ${name.padEnd(28)} → ${addr}`);
    return { contract, addr };
  };

  const { contract: issuerReg,   addr: issuerRegAddr  } = await deploy("IssuerRegistry");
  const { contract: didReg,      addr: didRegAddr      } = await deploy("DIDRegistry");
  const { contract: credReg,     addr: credRegAddr     } = await deploy("CredentialRegistry", issuerRegAddr);
  const { contract: docReg,      addr: docRegAddr      } = await deploy("DocumentProofRegistry");
  const { contract: revokeReg,   addr: revokeRegAddr   } = await deploy("RevocationRegistry", credRegAddr);
  const { contract: auditLedger, addr: auditLedgerAddr } = await deploy("AuditHashLedger");

  // ─── 2. Register Demo Issuers ─────────────────────────────────────────────
  console.log("\n🏛️  Registering Approved Issuers...\n");

  const ir = issuerReg.connect(deployer);

  const tx1 = await ir.registerIssuer(tuIssuer.address,   "Tribhuvan University", "university", "🏛️");
  await tx1.wait();
  console.log(`   ✅ Tribhuvan University registered  (${tuIssuer.address})`);

  const tx2 = await ir.registerIssuer(bankIssuer.address, "Nabil Bank",           "bank",       "🏦");
  await tx2.wait();
  console.log(`   ✅ Nabil Bank registered            (${bankIssuer.address})`);

  // ─── 3. Export ABIs to Backend ────────────────────────────────────────────
  console.log("\n💾 Exporting Contract ABIs to backend/src/contracts/ ...\n");

  const contractsDir = path.join(__dirname, "../backend/src/contracts");
  if (!fs.existsSync(contractsDir)) fs.mkdirSync(contractsDir, { recursive: true });

  const exports = [
    { name: "IssuerRegistry",        addr: issuerRegAddr   },
    { name: "DIDRegistry",           addr: didRegAddr      },
    { name: "CredentialRegistry",    addr: credRegAddr     },
    { name: "DocumentProofRegistry", addr: docRegAddr      },
    { name: "RevocationRegistry",    addr: revokeRegAddr   },
    { name: "AuditHashLedger",       addr: auditLedgerAddr },
  ];

  for (const c of exports) {
    const artifact = await hre.artifacts.readArtifact(c.name);
    fs.writeFileSync(
      path.join(contractsDir, `${c.name}.json`),
      JSON.stringify({ address: c.addr, abi: artifact.abi }, null, 2)
    );
    console.log(`   Saved ${c.name}.json`);
  }

  // ─── 4. Derive Hardhat Private Keys ───────────────────────────────────────
  // Hardhat uses a fixed development mnemonic — safe for local dev only
  const mnemonic = "test test test test test test test test test test test junk";
  const getPrivKey = (index) => {
    const wallet = hre.ethers.HDNodeWallet.fromMnemonic(
      hre.ethers.Mnemonic.fromPhrase(mnemonic),
      `m/44'/60'/0'/0/${index}`
    );
    return wallet.privateKey;
  };

  const adminPrivKey  = getPrivKey(0);
  const tuPrivKey     = getPrivKey(1);
  const bankPrivKey   = getPrivKey(2);
  const nirmalPrivKey = getPrivKey(3);

  // ─── 5. Write Backend .env ────────────────────────────────────────────────
  const backendDir = path.join(__dirname, "../backend");
  if (!fs.existsSync(backendDir)) fs.mkdirSync(backendDir, { recursive: true });

  const uploadsDir  = path.join(backendDir, "uploads");
  const encryptDir  = path.join(uploadsDir, "encrypted");
  if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
  if (!fs.existsSync(encryptDir)) fs.mkdirSync(encryptDir, { recursive: true });

  const envContent = `# ═══════════════════════════════════════════════════
# DIDPass Backend — Environment Configuration
# Auto-generated by scripts/deploy.js
# Date: ${new Date().toISOString()}
# ⚠️  NEVER commit this file to version control!
# ═══════════════════════════════════════════════════

# Server
NODE_ENV=development
PORT=4000

# Database (SQLite via Prisma — zero install needed)
DATABASE_URL="file:./didpass.db"

# JSON Web Tokens
JWT_SECRET=didpass-super-secret-jwt-key-CHANGE-IN-PRODUCTION-2024
CHAIN_ID=31337

# Blockchain (Local Hardhat Network)
HARDHAT_NETWORK_URL=http://127.0.0.1:8545

# ─── Wallet Private Keys ───────────────────────────────────
# ⚠️  These are Hardhat dev accounts ONLY — never use in production!
ADMIN_PRIVATE_KEY=${adminPrivKey}
TU_ISSUER_PRIVATE_KEY=${tuPrivKey}
BANK_ISSUER_PRIVATE_KEY=${bankPrivKey}
DEMO_HOLDER_PRIVATE_KEY=${nirmalPrivKey}

# ─── Wallet Addresses ──────────────────────────────────────
ADMIN_WALLET_ADDRESS=${deployer.address}
TU_ISSUER_ADDRESS=${tuIssuer.address}
BANK_ISSUER_ADDRESS=${bankIssuer.address}
DEMO_HOLDER_ADDRESS=${nirmal.address}

# ─── Smart Contract Addresses ──────────────────────────────
ISSUER_REGISTRY_ADDRESS=${issuerRegAddr}
DID_REGISTRY_ADDRESS=${didRegAddr}
CREDENTIAL_REGISTRY_ADDRESS=${credRegAddr}
DOCUMENT_PROOF_REGISTRY_ADDRESS=${docRegAddr}
REVOCATION_REGISTRY_ADDRESS=${revokeRegAddr}
AUDIT_HASH_LEDGER_ADDRESS=${auditLedgerAddr}

# ─── AES-256-GCM Encryption ────────────────────────────────
# 64 hex chars = 32 bytes = 256-bit key
ENCRYPTION_KEY=4a8f3c1d9b2e7f5a4a8f3c1d9b2e7f5a4a8f3c1d9b2e7f5a4a8f3c1d9b2e7f5a

# ─── Email (NodeMailer / Ethereal) ─────────────────────────
# Leave blank — backend auto-creates Ethereal test account on startup
EMAIL_HOST=smtp.ethereal.email
EMAIL_PORT=587
EMAIL_USER=
EMAIL_PASS=
EMAIL_FROM="DIDPass <noreply@didpass.io>"

# ─── Frontend URLs (CORS) ──────────────────────────────────
FRONTEND_DIDPASS_URL=http://localhost:3000
FRONTEND_UNIVERSITY_URL=http://localhost:3001

# ─── File Storage ──────────────────────────────────────────
UPLOAD_DIR=./uploads
`;

  fs.writeFileSync(path.join(backendDir, ".env"), envContent);
  console.log("\n✅ Backend .env written");
  console.log("✅ Upload directories created");

  // ─── 6. Summary ───────────────────────────────────────────────────────────
  console.log("\n" + "═".repeat(65));
  console.log("🎉  DEPLOYMENT COMPLETE!");
  console.log("═".repeat(65));

  console.log("\n📋 Contract Addresses:");
  for (const c of exports) console.log(`   ${c.name.padEnd(28)} ${c.addr}`);

  console.log("\n👤 Wallet Info:");
  console.log(`   Admin:   ${deployer.address}`);
  console.log(`   TU:      ${tuIssuer.address}`);
  console.log(`   Nabil:   ${bankIssuer.address}`);
  console.log(`   Nirmal:  ${nirmal.address}`);

  console.log("\n🔑 MetaMask Setup (add this network):");
  console.log(`   Network Name: Hardhat Local`);
  console.log(`   RPC URL:      http://127.0.0.1:8545`);
  console.log(`   Chain ID:     31337`);
  console.log(`   Symbol:       ETH`);

  console.log("\n🚀 Import Nirmal's wallet into MetaMask:");
  console.log(`   Private Key: ${nirmalPrivKey}`);

  console.log("\n📖 Next Steps:");
  console.log(`   Terminal 1: npx hardhat node  (already running)`);
  console.log(`   Terminal 2: cd backend && npx prisma migrate dev --name init && npm run dev`);
  console.log(`   Terminal 3: cd frontend-didpass && npm install && npm run dev`);
  console.log(`   Terminal 4: cd university-portal && npm install && npm run dev`);
  console.log("\n" + "═".repeat(65));
}

main()
  .then(() => process.exit(0))
  .catch((error) => { console.error("\n❌ Deployment failed:", error); process.exit(1); });
